name: ci
"on":
  pull_request: {}
  push:
    branches:
    - staging
    - trying
    - master
jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
    - name: Fetch sources
      uses: actions/checkout@v2
    - name: Run linter
      uses: golangci/golangci-lint-action@v2
      with:
        args: --enable=gofmt
        version: latest
  misspell:
    runs-on: ubuntu-20.04
    steps:
    - name: Fetch sources
      uses: actions/checkout@v2
    - name: run spellcheck
      uses: reviewdog/action-misspell@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        locale: US
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
    - name: Fetch sources
      uses: actions/checkout@v2
    - name: Install golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
    - name: Run tests
      run: go test .
